import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import  PageTransition  from "@components/PageTransition";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
        />
      </head>

       <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* Contenedor para animación */}
          <div id="page-container">{children}</div>
        </body>
    </html>
  );
}
